export interface CompleteUserRegistration {
  id: number;
  vatNumber: string;
  businessName: string;
  address: string;
  city: string;
  zipCode: string;
  mobile: string;
  pec: string;
  usernamePoste: string;
  passwordPoste: string;
  contractStartDate?: string | null;
  contractEndDate?: string | null;
  email: string;
  password: string;  
  molContractCode: string;
  col1ContractCode: string;
  col4ContractCode: string;
  volContractCode: string;
  agolBContractCode: string;
  agolMContractCode: string;
  hidePrice: string;
  rr: string;
  ged: string;
  usernamePosteGed: string;
  passwordPosteGed: string;
  usernameOldSite?: string;
  passwordOldSite?: string;
  doubleFactor: string;
}
